# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Key by Rack5
email: peter@keyauth.com
description: > # this means to ignore newlines until "baseurl:"
  The easiest way to lock and unlock your Mac. Put your iPhone in your pocket and walk away.
baseurl: "/key" # the subpath of your site, e.g. /blog
url: "http://rack5.co/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: keyauth
facebook_username: keyauth
github_username:  rack5

collections:
  docs:
    output: true

# Build settings
markdown: kramdown
theme: minima

paginate: 4
paginate_path: "/updates/:num/"

gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
